# Generated by Django 2.2.9 on 2024-05-01 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CelularesBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('preco', models.CharField(blank=True, max_length=6)),
                ('criacao', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Celular',
                'verbose_name_plural': 'Celulares',
                'ordering': ['ano'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('criacao', models.DateTimeField(auto_now=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('comentario', models.TextField(blank=True, default='')),
                ('avaliacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('avaliacao', models.DecimalField(decimal_places=1, max_digits=2)),
                ('celular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='celulares.CelularesBase')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'unique_together': {('email', 'celular')},
            },
        ),
    ]
