# Generated by Django 2.2.9 on 2024-04-24 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CelularesBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('preco', models.FloatField()),
            ],
            options={
                'verbose_name': 'Celular',
                'verbose_name_plural': 'Celulares',
                'ordering': ['ano'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('celularesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='celulares.CelularesBase')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('comentario', models.TextField(default='', null=True)),
                ('avaliacaonum', models.DecimalField(decimal_places=1, max_digits=2)),
                ('celular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='celulares.CelularesBase')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'unique_together': {('celular', 'email')},
            },
            bases=('celulares.celularesbase',),
        ),
    ]
