# Generated by Django 2.2.9 on 2024-04-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celulares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celularesbase',
            name='preco',
            field=models.CharField(default='', max_length=6, null=True),
        ),
    ]
